-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity decode_castOut is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    full_out_float9_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    full_out_float9_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    full_out_float9_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    full_out_float9_empty_n : IN STD_LOGIC;
    full_out_float9_read : OUT STD_LOGIC;
    full_out_AXI_TREADY : IN STD_LOGIC;
    full_out_AXI_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    full_out_AXI_TVALID : OUT STD_LOGIC;
    full_out_AXI_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    full_out_AXI_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    full_out_AXI_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    full_out_AXI_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    full_out_AXI_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    full_out_AXI_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of decode_castOut is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal regslice_both_full_out_AXI_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln23_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal full_out_float9_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal full_out_AXI_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_64 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_2_fu_120_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal full_out_AXI_TVALID_int_regslice : STD_LOGIC;
    signal full_out_AXI_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_full_out_AXI_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_condition_110 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component decode_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component decode_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component decode_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_full_out_AXI_V_data_V_U : component decode_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => full_out_float9_dout,
        vld_in => full_out_AXI_TVALID_int_regslice,
        ack_in => full_out_AXI_TREADY_int_regslice,
        data_out => full_out_AXI_TDATA,
        vld_out => regslice_both_full_out_AXI_V_data_V_U_vld_out,
        ack_out => full_out_AXI_TREADY,
        apdone_blk => regslice_both_full_out_AXI_V_data_V_U_apdone_blk);

    regslice_both_full_out_AXI_V_keep_V_U : component decode_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv4_0,
        vld_in => full_out_AXI_TVALID_int_regslice,
        ack_in => regslice_both_full_out_AXI_V_keep_V_U_ack_in_dummy,
        data_out => full_out_AXI_TKEEP,
        vld_out => regslice_both_full_out_AXI_V_keep_V_U_vld_out,
        ack_out => full_out_AXI_TREADY,
        apdone_blk => regslice_both_full_out_AXI_V_keep_V_U_apdone_blk);

    regslice_both_full_out_AXI_V_strb_V_U : component decode_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv4_0,
        vld_in => full_out_AXI_TVALID_int_regslice,
        ack_in => regslice_both_full_out_AXI_V_strb_V_U_ack_in_dummy,
        data_out => full_out_AXI_TSTRB,
        vld_out => regslice_both_full_out_AXI_V_strb_V_U_vld_out,
        ack_out => full_out_AXI_TREADY,
        apdone_blk => regslice_both_full_out_AXI_V_strb_V_U_apdone_blk);

    regslice_both_full_out_AXI_V_user_V_U : component decode_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv2_0,
        vld_in => full_out_AXI_TVALID_int_regslice,
        ack_in => regslice_both_full_out_AXI_V_user_V_U_ack_in_dummy,
        data_out => full_out_AXI_TUSER,
        vld_out => regslice_both_full_out_AXI_V_user_V_U_vld_out,
        ack_out => full_out_AXI_TREADY,
        apdone_blk => regslice_both_full_out_AXI_V_user_V_U_apdone_blk);

    regslice_both_full_out_AXI_V_last_V_U : component decode_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv1_0,
        vld_in => full_out_AXI_TVALID_int_regslice,
        ack_in => regslice_both_full_out_AXI_V_last_V_U_ack_in_dummy,
        data_out => full_out_AXI_TLAST,
        vld_out => regslice_both_full_out_AXI_V_last_V_U_vld_out,
        ack_out => full_out_AXI_TREADY,
        apdone_blk => regslice_both_full_out_AXI_V_last_V_U_apdone_blk);

    regslice_both_full_out_AXI_V_id_V_U : component decode_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv5_0,
        vld_in => full_out_AXI_TVALID_int_regslice,
        ack_in => regslice_both_full_out_AXI_V_id_V_U_ack_in_dummy,
        data_out => full_out_AXI_TID,
        vld_out => regslice_both_full_out_AXI_V_id_V_U_vld_out,
        ack_out => full_out_AXI_TREADY,
        apdone_blk => regslice_both_full_out_AXI_V_id_V_U_apdone_blk);

    regslice_both_full_out_AXI_V_dest_V_U : component decode_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv6_0,
        vld_in => full_out_AXI_TVALID_int_regslice,
        ack_in => regslice_both_full_out_AXI_V_dest_V_U_ack_in_dummy,
        data_out => full_out_AXI_TDEST,
        vld_out => regslice_both_full_out_AXI_V_dest_V_U_vld_out,
        ack_out => full_out_AXI_TREADY,
        apdone_blk => regslice_both_full_out_AXI_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_110)) then
                if ((icmp_ln23_fu_114_p2 = ap_const_lv1_0)) then 
                    i_fu_64 <= i_2_fu_120_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_64 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, full_out_float9_empty_n, regslice_both_full_out_AXI_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, full_out_AXI_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_full_out_AXI_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (full_out_AXI_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_full_out_AXI_V_data_V_U_apdone_blk = ap_const_logic_1) or (full_out_float9_empty_n = ap_const_logic_0) or (full_out_AXI_TREADY_int_regslice = ap_const_logic_0))) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, full_out_float9_empty_n, regslice_both_full_out_AXI_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, full_out_AXI_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_full_out_AXI_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (full_out_AXI_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_full_out_AXI_V_data_V_U_apdone_blk = ap_const_logic_1) or (full_out_float9_empty_n = ap_const_logic_0) or (full_out_AXI_TREADY_int_regslice = ap_const_logic_0))) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, full_out_float9_empty_n, regslice_both_full_out_AXI_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, full_out_AXI_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_full_out_AXI_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (full_out_AXI_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_full_out_AXI_V_data_V_U_apdone_blk = ap_const_logic_1) or (full_out_float9_empty_n = ap_const_logic_0) or (full_out_AXI_TREADY_int_regslice = ap_const_logic_0))) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(full_out_float9_empty_n, regslice_both_full_out_AXI_V_data_V_U_apdone_blk, full_out_AXI_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((regslice_both_full_out_AXI_V_data_V_U_apdone_blk = ap_const_logic_1) or (full_out_float9_empty_n = ap_const_logic_0) or (full_out_AXI_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(full_out_AXI_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (full_out_AXI_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_condition_110_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_110 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln23_fu_114_p2, ap_start_int)
    begin
        if (((icmp_ln23_fu_114_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_64, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_64;
        end if; 
    end process;


    full_out_AXI_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, full_out_AXI_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            full_out_AXI_TDATA_blk_n <= full_out_AXI_TREADY_int_regslice;
        else 
            full_out_AXI_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    full_out_AXI_TVALID <= regslice_both_full_out_AXI_V_data_V_U_vld_out;

    full_out_AXI_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            full_out_AXI_TVALID_int_regslice <= ap_const_logic_1;
        else 
            full_out_AXI_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    full_out_float9_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, full_out_float9_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            full_out_float9_blk_n <= full_out_float9_empty_n;
        else 
            full_out_float9_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    full_out_float9_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            full_out_float9_read <= ap_const_logic_1;
        else 
            full_out_float9_read <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_120_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv10_1));
    icmp_ln23_fu_114_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv10_310) else "0";
end behav;
