-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity decode_upsamp5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv5_out_dout : IN STD_LOGIC_VECTOR (39 downto 0);
    conv5_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    conv5_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    conv5_out_empty_n : IN STD_LOGIC;
    conv5_out_read : OUT STD_LOGIC;
    upsamp5_out_din : OUT STD_LOGIC_VECTOR (39 downto 0);
    upsamp5_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    upsamp5_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    upsamp5_out_full_n : IN STD_LOGIC;
    upsamp5_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of decode_upsamp5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal icmp_ln76_reg_475 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_508 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op99_read_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage7_iter0 : BOOLEAN;
    signal ap_block_state16_pp0_stage7_iter1 : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage7 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal conv5_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal ap_block_pp0_stage7 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal upsamp5_out_blk_n : STD_LOGIC;
    signal icmp_ln76_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op106_read_state9 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln76_fu_266_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln76_reg_479 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln76_fu_284_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln76_reg_484 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln76_2_fu_298_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln76_2_reg_489 : STD_LOGIC_VECTOR (4 downto 0);
    signal div15_i_udiv_reg_494 : STD_LOGIC_VECTOR (3 downto 0);
    signal div15_i_udiv_cast_cast_reg_503 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op47_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state10_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal conv5_out_read_reg_517 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_predicate_op56_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state11_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal zext_ln84_17_cast_fu_356_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln84_17_cast_reg_527 : STD_LOGIC_VECTOR (4 downto 0);
    signal upsam_buf_addr_18_reg_532 : STD_LOGIC_VECTOR (5 downto 0);
    signal conv5_out_read_1_reg_537 : STD_LOGIC_VECTOR (39 downto 0);
    signal upsam_buf5_q0 : STD_LOGIC_VECTOR (39 downto 0);
    signal upsam_buf_load_reg_542 : STD_LOGIC_VECTOR (39 downto 0);
    signal xor_ln84_fu_371_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal xor_ln84_reg_547 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_predicate_op69_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_state12_pp0_stage3_iter1 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal upsam_buf_addr_19_reg_553 : STD_LOGIC_VECTOR (5 downto 0);
    signal upsam_buf_addr_20_reg_558 : STD_LOGIC_VECTOR (5 downto 0);
    signal conv5_out_read_2_reg_563 : STD_LOGIC_VECTOR (39 downto 0);
    signal upsam_buf_load_16_reg_568 : STD_LOGIC_VECTOR (39 downto 0);
    signal upsam_buf5_q1 : STD_LOGIC_VECTOR (39 downto 0);
    signal upsam_buf_load_17_reg_573 : STD_LOGIC_VECTOR (39 downto 0);
    signal upsam_buf_addr_21_reg_578 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_predicate_op86_read_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal ap_block_state13_pp0_stage4_iter1 : BOOLEAN;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal upsam_buf_addr_22_reg_584 : STD_LOGIC_VECTOR (5 downto 0);
    signal conv5_out_read_3_reg_590 : STD_LOGIC_VECTOR (39 downto 0);
    signal upsam_buf_load_18_reg_595 : STD_LOGIC_VECTOR (39 downto 0);
    signal upsam_buf_load_19_reg_600 : STD_LOGIC_VECTOR (39 downto 0);
    signal conv5_out_read_4_reg_605 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_predicate_op92_read_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage5_iter0 : BOOLEAN;
    signal ap_block_state14_pp0_stage5_iter1 : BOOLEAN;
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal conv5_out_read_5_reg_620 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_predicate_op97_read_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage6_iter0 : BOOLEAN;
    signal ap_block_state15_pp0_stage6_iter1 : BOOLEAN;
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal ap_block_pp0_stage7_11001 : BOOLEAN;
    signal upsam_buf_load_22_reg_635 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal upsam_buf5_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal upsam_buf5_ce0 : STD_LOGIC;
    signal upsam_buf5_we0 : STD_LOGIC;
    signal upsam_buf5_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal upsam_buf5_ce1 : STD_LOGIC;
    signal upsam_buf5_we1 : STD_LOGIC;
    signal ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i571115212735_reg_172 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i571115212735_reg_172 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_181016202834_reg_182 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_181016202834_reg_182 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_21214222636_reg_192 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_21214222636_reg_192 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_317192933_reg_202 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_317192933_reg_202 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_4232537_reg_212 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_4232537_reg_212 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_53032_reg_222 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_53032_reg_222 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_638_reg_232 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_638_reg_232 : STD_LOGIC_VECTOR (39 downto 0);
    signal zext_ln84_fu_340_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln84_16_fu_351_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln84_17_fu_363_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln84_18_fu_380_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln84_19_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln84_20_fu_407_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln84_21_fu_415_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln82_fu_441_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln84_22_fu_449_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal cona_col_fu_68 : STD_LOGIC_VECTOR (4 downto 0);
    signal cona_col_2_fu_420_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_cona_col_load : STD_LOGIC_VECTOR (4 downto 0);
    signal cona_row_fu_72 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_cona_row_load : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_fu_76 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal ap_block_pp0_stage3_01001 : BOOLEAN;
    signal ap_block_pp0_stage4_01001 : BOOLEAN;
    signal ap_block_pp0_stage5_01001 : BOOLEAN;
    signal ap_block_pp0_stage6_01001 : BOOLEAN;
    signal ap_block_pp0_stage7_01001 : BOOLEAN;
    signal icmp_ln77_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln76_2_fu_292_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln77_fu_310_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln76_fu_306_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln84_16_cast_fu_344_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln84_fu_376_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal div15_i_udiv_cast_fu_368_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln84_19_cast_fu_385_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal div15_i_udiv_cast1_fu_398_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln84_fu_401_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln84_4_fu_412_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln82_fu_438_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln84_5_fu_446_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_378 : BOOLEAN;
    signal ap_condition_735 : BOOLEAN;
    signal ap_condition_739 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component decode_upsamp5_upsam_buf5_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (39 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (39 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (39 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;


    component decode_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    upsam_buf5_U : component decode_upsamp5_upsam_buf5_RAM_AUTO_1R1W
    generic map (
        DataWidth => 40,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => upsam_buf5_address0,
        ce0 => upsam_buf5_ce0,
        we0 => upsam_buf5_we0,
        d0 => conv5_out_dout,
        q0 => upsam_buf5_q0,
        address1 => upsam_buf5_address1,
        ce1 => upsam_buf5_ce1,
        we1 => upsam_buf5_we1,
        d1 => conv5_out_dout,
        q1 => upsam_buf5_q1);

    flow_control_loop_pipe_U : component decode_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage7,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage7)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i571115212735_reg_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_378)) then
                if (((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i571115212735_reg_172 <= conv5_out_read_reg_517;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i571115212735_reg_172 <= ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i571115212735_reg_172;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_181016202834_reg_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_378)) then
                if (((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_181016202834_reg_182 <= conv5_out_read_1_reg_537;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_181016202834_reg_182 <= ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_181016202834_reg_182;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_21214222636_reg_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_378)) then
                if (((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_21214222636_reg_192 <= conv5_out_read_2_reg_563;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_21214222636_reg_192 <= ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_21214222636_reg_192;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_317192933_reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_378)) then
                if (((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_317192933_reg_202 <= conv5_out_read_3_reg_590;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_317192933_reg_202 <= ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_317192933_reg_202;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_4232537_reg_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_378)) then
                if (((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_4232537_reg_212 <= conv5_out_read_4_reg_605;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_4232537_reg_212 <= ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_4232537_reg_212;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_53032_reg_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_378)) then
                if (((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_53032_reg_222 <= conv5_out_read_5_reg_620;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_53032_reg_222 <= ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_53032_reg_222;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_638_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_378)) then
                if (((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_638_reg_232 <= conv5_out_dout;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_638_reg_232 <= ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_638_reg_232;
                end if;
            end if; 
        end if;
    end process;

    cona_col_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_739)) then 
                    cona_col_fu_68 <= ap_const_lv5_0;
                elsif ((ap_const_boolean_1 = ap_condition_735)) then 
                    cona_col_fu_68 <= cona_col_2_fu_420_p2;
                end if;
            end if; 
        end if;
    end process;

    cona_row_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_739)) then 
                    cona_row_fu_72 <= ap_const_lv5_0;
                elsif ((ap_const_boolean_1 = ap_condition_735)) then 
                    cona_row_fu_72 <= select_ln76_2_reg_489;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_739)) then 
                    indvar_flatten_fu_76 <= ap_const_lv9_0;
                elsif ((ap_const_boolean_1 = ap_condition_735)) then 
                    indvar_flatten_fu_76 <= add_ln76_reg_479;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln76_reg_479 <= add_ln76_fu_266_p2;
                icmp_ln76_reg_475 <= icmp_ln76_fu_260_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i571115212735_reg_172 <= upsam_buf_load_reg_542;
                ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_181016202834_reg_182 <= upsam_buf_load_16_reg_568;
                ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_21214222636_reg_192 <= upsam_buf_load_17_reg_573;
                ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_317192933_reg_202 <= upsam_buf_load_18_reg_595;
                ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_4232537_reg_212 <= upsam_buf_load_19_reg_600;
                ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_53032_reg_222 <= upsam_buf5_q1;
                ap_phi_reg_pp0_iter0_arrayidx18_0_0_0_load_i_638_reg_232 <= upsam_buf5_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op56_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                conv5_out_read_1_reg_537 <= conv5_out_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op69_read_state4 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                conv5_out_read_2_reg_563 <= conv5_out_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op86_read_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                conv5_out_read_3_reg_590 <= conv5_out_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op92_read_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                conv5_out_read_4_reg_605 <= conv5_out_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_predicate_op97_read_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                conv5_out_read_5_reg_620 <= conv5_out_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op47_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                conv5_out_read_reg_517 <= conv5_out_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln76_fu_260_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                div15_i_udiv_cast_cast_reg_503 <= select_ln76_fu_284_p3(3 downto 1);
                div15_i_udiv_reg_494 <= select_ln76_fu_284_p3(4 downto 1);
                empty_reg_508 <= empty_fu_334_p2;
                select_ln76_2_reg_489 <= select_ln76_2_fu_298_p3;
                select_ln76_reg_484 <= select_ln76_fu_284_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                    upsam_buf_addr_18_reg_532(3 downto 0) <= zext_ln84_17_fu_363_p1(6 - 1 downto 0)(3 downto 0);
                    zext_ln84_17_cast_reg_527(3 downto 0) <= zext_ln84_17_cast_fu_356_p3(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                    upsam_buf_addr_19_reg_553(4 downto 0) <= zext_ln84_18_fu_380_p1(6 - 1 downto 0)(4 downto 0);
                    upsam_buf_addr_20_reg_558(3 downto 0) <= zext_ln84_19_fu_393_p1(6 - 1 downto 0)(3 downto 0);
                xor_ln84_reg_547 <= xor_ln84_fu_371_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                upsam_buf_addr_21_reg_578 <= zext_ln84_20_fu_407_p1(6 - 1 downto 0);
                    upsam_buf_addr_22_reg_584(3 downto 0) <= zext_ln84_21_fu_415_p1(6 - 1 downto 0)(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                upsam_buf_load_16_reg_568 <= upsam_buf5_q0;
                upsam_buf_load_17_reg_573 <= upsam_buf5_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                upsam_buf_load_18_reg_595 <= upsam_buf5_q0;
                upsam_buf_load_19_reg_600 <= upsam_buf5_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                upsam_buf_load_22_reg_635 <= upsam_buf5_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                upsam_buf_load_reg_542 <= upsam_buf5_q0;
            end if;
        end if;
    end process;
    zext_ln84_17_cast_reg_527(4) <= '1';
    upsam_buf_addr_18_reg_532(5 downto 4) <= "01";
    upsam_buf_addr_19_reg_553(5) <= '0';
    upsam_buf_addr_20_reg_558(5 downto 4) <= "10";
    upsam_buf_addr_22_reg_584(5 downto 4) <= "11";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage7_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln76_2_fu_292_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_cona_row_load) + unsigned(ap_const_lv5_1));
    add_ln76_fu_266_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv9_1));
    add_ln84_fu_401_p2 <= std_logic_vector(unsigned(div15_i_udiv_cast1_fu_398_p1) + unsigned(ap_const_lv6_28));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_done_reg, ap_predicate_op106_read_state9)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((upsamp5_out_full_n = ap_const_logic_0) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op106_read_state9 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_done_reg = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_done_reg, ap_predicate_op106_read_state9)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((upsamp5_out_full_n = ap_const_logic_0) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op106_read_state9 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_done_reg = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_done_reg, ap_predicate_op106_read_state9)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((upsamp5_out_full_n = ap_const_logic_0) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op106_read_state9 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_done_reg = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op47_read_state2)
    begin
                ap_block_pp0_stage1_01001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op47_read_state2 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op47_read_state2)
    begin
                ap_block_pp0_stage1_11001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op47_read_state2 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op47_read_state2)
    begin
                ap_block_pp0_stage1_subdone <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op47_read_state2 = ap_const_boolean_1)));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op56_read_state3)
    begin
                ap_block_pp0_stage2_01001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op56_read_state3 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op56_read_state3)
    begin
                ap_block_pp0_stage2_11001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op56_read_state3 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op56_read_state3)
    begin
                ap_block_pp0_stage2_subdone <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op56_read_state3 = ap_const_boolean_1)));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op69_read_state4)
    begin
                ap_block_pp0_stage3_01001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op69_read_state4 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op69_read_state4)
    begin
                ap_block_pp0_stage3_11001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op69_read_state4 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op69_read_state4)
    begin
                ap_block_pp0_stage3_subdone <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op69_read_state4 = ap_const_boolean_1)));
    end process;

        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op86_read_state5)
    begin
                ap_block_pp0_stage4_01001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op86_read_state5 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage4_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op86_read_state5)
    begin
                ap_block_pp0_stage4_11001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op86_read_state5 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op86_read_state5)
    begin
                ap_block_pp0_stage4_subdone <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op86_read_state5 = ap_const_boolean_1)));
    end process;

        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op92_read_state6)
    begin
                ap_block_pp0_stage5_01001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op92_read_state6 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage5_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op92_read_state6)
    begin
                ap_block_pp0_stage5_11001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op92_read_state6 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage5_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op92_read_state6)
    begin
                ap_block_pp0_stage5_subdone <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op92_read_state6 = ap_const_boolean_1)));
    end process;

        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage6_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op97_read_state7)
    begin
                ap_block_pp0_stage6_01001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op97_read_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage6_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op97_read_state7)
    begin
                ap_block_pp0_stage6_11001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op97_read_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage6_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op97_read_state7)
    begin
                ap_block_pp0_stage6_subdone <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op97_read_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, ap_predicate_op99_read_state8, upsamp5_out_full_n)
    begin
                ap_block_pp0_stage7_01001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_predicate_op99_read_state8 = ap_const_boolean_1) and (conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage7_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, ap_predicate_op99_read_state8, upsamp5_out_full_n)
    begin
                ap_block_pp0_stage7_11001 <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_predicate_op99_read_state8 = ap_const_boolean_1) and (conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage7_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, conv5_out_empty_n, ap_predicate_op99_read_state8, upsamp5_out_full_n)
    begin
                ap_block_pp0_stage7_subdone <= (((upsamp5_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_predicate_op99_read_state8 = ap_const_boolean_1) and (conv5_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_state10_pp0_stage1_iter1_assign_proc : process(upsamp5_out_full_n)
    begin
                ap_block_state10_pp0_stage1_iter1 <= (upsamp5_out_full_n = ap_const_logic_0);
    end process;


    ap_block_state11_pp0_stage2_iter1_assign_proc : process(upsamp5_out_full_n)
    begin
                ap_block_state11_pp0_stage2_iter1 <= (upsamp5_out_full_n = ap_const_logic_0);
    end process;


    ap_block_state12_pp0_stage3_iter1_assign_proc : process(upsamp5_out_full_n)
    begin
                ap_block_state12_pp0_stage3_iter1 <= (upsamp5_out_full_n = ap_const_logic_0);
    end process;


    ap_block_state13_pp0_stage4_iter1_assign_proc : process(upsamp5_out_full_n)
    begin
                ap_block_state13_pp0_stage4_iter1 <= (upsamp5_out_full_n = ap_const_logic_0);
    end process;


    ap_block_state14_pp0_stage5_iter1_assign_proc : process(upsamp5_out_full_n)
    begin
                ap_block_state14_pp0_stage5_iter1 <= (upsamp5_out_full_n = ap_const_logic_0);
    end process;


    ap_block_state15_pp0_stage6_iter1_assign_proc : process(upsamp5_out_full_n)
    begin
                ap_block_state15_pp0_stage6_iter1 <= (upsamp5_out_full_n = ap_const_logic_0);
    end process;


    ap_block_state16_pp0_stage7_iter1_assign_proc : process(upsamp5_out_full_n)
    begin
                ap_block_state16_pp0_stage7_iter1 <= (upsamp5_out_full_n = ap_const_logic_0);
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(conv5_out_empty_n, ap_predicate_op47_read_state2)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op47_read_state2 = ap_const_boolean_1));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(conv5_out_empty_n, ap_predicate_op56_read_state3)
    begin
                ap_block_state3_pp0_stage2_iter0 <= ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op56_read_state3 = ap_const_boolean_1));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(conv5_out_empty_n, ap_predicate_op69_read_state4)
    begin
                ap_block_state4_pp0_stage3_iter0 <= ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op69_read_state4 = ap_const_boolean_1));
    end process;


    ap_block_state5_pp0_stage4_iter0_assign_proc : process(conv5_out_empty_n, ap_predicate_op86_read_state5)
    begin
                ap_block_state5_pp0_stage4_iter0 <= ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op86_read_state5 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp0_stage5_iter0_assign_proc : process(conv5_out_empty_n, ap_predicate_op92_read_state6)
    begin
                ap_block_state6_pp0_stage5_iter0 <= ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op92_read_state6 = ap_const_boolean_1));
    end process;


    ap_block_state7_pp0_stage6_iter0_assign_proc : process(conv5_out_empty_n, ap_predicate_op97_read_state7)
    begin
                ap_block_state7_pp0_stage6_iter0 <= ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op97_read_state7 = ap_const_boolean_1));
    end process;


    ap_block_state8_pp0_stage7_iter0_assign_proc : process(conv5_out_empty_n, ap_predicate_op99_read_state8)
    begin
                ap_block_state8_pp0_stage7_iter0 <= ((ap_predicate_op99_read_state8 = ap_const_boolean_1) and (conv5_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_state9_pp0_stage0_iter1_assign_proc : process(conv5_out_empty_n, upsamp5_out_full_n, ap_predicate_op106_read_state9)
    begin
                ap_block_state9_pp0_stage0_iter1 <= ((upsamp5_out_full_n = ap_const_logic_0) or ((conv5_out_empty_n = ap_const_logic_0) and (ap_predicate_op106_read_state9 = ap_const_boolean_1)));
    end process;


    ap_condition_378_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_11001)
    begin
                ap_condition_378 <= ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7));
    end process;


    ap_condition_735_assign_proc : process(ap_CS_fsm_pp0_stage7, icmp_ln76_reg_475, ap_block_pp0_stage7_11001)
    begin
                ap_condition_735 <= ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7));
    end process;


    ap_condition_739_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_loop_init)
    begin
                ap_condition_739 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage7_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, icmp_ln76_reg_475, ap_block_pp0_stage7_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (icmp_ln76_reg_475 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_condition_exit_pp0_iter0_stage7 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage7;

    ap_predicate_op106_read_state9_assign_proc : process(icmp_ln76_reg_475, empty_reg_508)
    begin
                ap_predicate_op106_read_state9 <= ((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0));
    end process;


    ap_predicate_op47_read_state2_assign_proc : process(icmp_ln76_reg_475, empty_reg_508)
    begin
                ap_predicate_op47_read_state2 <= ((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0));
    end process;


    ap_predicate_op56_read_state3_assign_proc : process(icmp_ln76_reg_475, empty_reg_508)
    begin
                ap_predicate_op56_read_state3 <= ((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0));
    end process;


    ap_predicate_op69_read_state4_assign_proc : process(icmp_ln76_reg_475, empty_reg_508)
    begin
                ap_predicate_op69_read_state4 <= ((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0));
    end process;


    ap_predicate_op86_read_state5_assign_proc : process(icmp_ln76_reg_475, empty_reg_508)
    begin
                ap_predicate_op86_read_state5 <= ((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0));
    end process;


    ap_predicate_op92_read_state6_assign_proc : process(icmp_ln76_reg_475, empty_reg_508)
    begin
                ap_predicate_op92_read_state6 <= ((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0));
    end process;


    ap_predicate_op97_read_state7_assign_proc : process(icmp_ln76_reg_475, empty_reg_508)
    begin
                ap_predicate_op97_read_state7 <= ((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0));
    end process;


    ap_predicate_op99_read_state8_assign_proc : process(icmp_ln76_reg_475, empty_reg_508)
    begin
                ap_predicate_op99_read_state8 <= ((empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_cona_col_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, cona_col_fu_68, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_cona_col_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_cona_col_load <= cona_col_fu_68;
        end if; 
    end process;


    ap_sig_allocacmp_cona_row_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, cona_row_fu_72)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_cona_row_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_cona_row_load <= cona_row_fu_72;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_76)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_76;
        end if; 
    end process;

    cona_col_2_fu_420_p2 <= std_logic_vector(unsigned(select_ln76_reg_484) + unsigned(ap_const_lv5_1));

    conv5_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, conv5_out_empty_n, icmp_ln76_reg_475, empty_reg_508, ap_predicate_op99_read_state8, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6, ap_block_pp0_stage7, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_predicate_op99_read_state8 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage6) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage5) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage4) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) 
    and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            conv5_out_blk_n <= conv5_out_empty_n;
        else 
            conv5_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv5_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, ap_predicate_op99_read_state8, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_predicate_op106_read_state9, ap_block_pp0_stage0_11001, ap_predicate_op47_read_state2, ap_block_pp0_stage1_11001, ap_predicate_op56_read_state3, ap_block_pp0_stage2_11001, ap_predicate_op69_read_state4, ap_block_pp0_stage3_11001, ap_predicate_op86_read_state5, ap_block_pp0_stage4_11001, ap_predicate_op92_read_state6, ap_block_pp0_stage5_11001, ap_predicate_op97_read_state7, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_predicate_op99_read_state8 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_predicate_op97_read_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op92_read_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op86_read_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op69_read_state4 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) 
    or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op56_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op47_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_predicate_op106_read_state9 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            conv5_out_read <= ap_const_logic_1;
        else 
            conv5_out_read <= ap_const_logic_0;
        end if; 
    end process;

    div15_i_udiv_cast1_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(div15_i_udiv_reg_494),6));
    div15_i_udiv_cast_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(div15_i_udiv_reg_494),5));
    empty_fu_334_p2 <= (trunc_ln77_fu_310_p1 or trunc_ln76_fu_306_p1);
    icmp_ln76_fu_260_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv9_100) else "0";
    icmp_ln77_fu_278_p2 <= "1" when (ap_sig_allocacmp_cona_col_load = ap_const_lv5_10) else "0";

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln76_2_fu_298_p3 <= 
        add_ln76_2_fu_292_p2 when (icmp_ln77_fu_278_p2(0) = '1') else 
        ap_sig_allocacmp_cona_row_load;
    select_ln76_fu_284_p3 <= 
        ap_const_lv5_0 when (icmp_ln77_fu_278_p2(0) = '1') else 
        ap_sig_allocacmp_cona_col_load;
        sext_ln82_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(xor_ln84_reg_547),6));

        sext_ln84_4_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(zext_ln84_17_cast_reg_527),6));

        sext_ln84_5_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(xor_ln84_reg_547),6));

        sext_ln84_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(xor_ln84_fu_371_p2),5));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln76_fu_306_p1 <= select_ln76_2_fu_298_p3(1 - 1 downto 0);
    trunc_ln77_fu_310_p1 <= select_ln76_fu_284_p3(1 - 1 downto 0);

    upsam_buf5_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, icmp_ln76_reg_475, empty_reg_508, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6, ap_block_pp0_stage0, upsam_buf_addr_19_reg_553, upsam_buf_addr_21_reg_578, zext_ln84_fu_340_p1, zext_ln84_16_fu_351_p1, zext_ln84_18_fu_380_p1, zext_ln84_21_fu_415_p1, zext_ln82_fu_441_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            upsam_buf5_address0 <= zext_ln82_fu_441_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            upsam_buf5_address0 <= upsam_buf_addr_21_reg_578;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage4) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            upsam_buf5_address0 <= zext_ln84_21_fu_415_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage4) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            upsam_buf5_address0 <= upsam_buf_addr_19_reg_553;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            upsam_buf5_address0 <= zext_ln84_18_fu_380_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            upsam_buf5_address0 <= zext_ln84_16_fu_351_p1(6 - 1 downto 0);
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage1) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            upsam_buf5_address0 <= zext_ln84_fu_340_p1(6 - 1 downto 0);
        else 
            upsam_buf5_address0 <= "XXXXXX";
        end if; 
    end process;


    upsam_buf5_address1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, icmp_ln76_reg_475, empty_reg_508, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5, ap_block_pp0_stage7, upsam_buf_addr_18_reg_532, upsam_buf_addr_20_reg_558, upsam_buf_addr_22_reg_584, zext_ln84_16_fu_351_p1, zext_ln84_17_fu_363_p1, zext_ln84_19_fu_393_p1, zext_ln84_20_fu_407_p1, zext_ln84_22_fu_449_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            upsam_buf5_address1 <= zext_ln84_22_fu_449_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            upsam_buf5_address1 <= upsam_buf_addr_22_reg_584;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            upsam_buf5_address1 <= upsam_buf_addr_20_reg_558;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            upsam_buf5_address1 <= zext_ln84_20_fu_407_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            upsam_buf5_address1 <= zext_ln84_19_fu_393_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            upsam_buf5_address1 <= upsam_buf_addr_18_reg_532;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            upsam_buf5_address1 <= zext_ln84_17_fu_363_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            upsam_buf5_address1 <= zext_ln84_16_fu_351_p1(6 - 1 downto 0);
        else 
            upsam_buf5_address1 <= "XXXXXX";
        end if; 
    end process;


    upsam_buf5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, icmp_ln76_reg_475, empty_reg_508, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001, ap_block_pp0_stage6_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) 
    and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            upsam_buf5_ce0 <= ap_const_logic_1;
        else 
            upsam_buf5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    upsam_buf5_ce1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, icmp_ln76_reg_475, empty_reg_508, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001, ap_block_pp0_stage5_11001, ap_block_pp0_stage7_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) 
    and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (empty_reg_508 = ap_const_lv1_1) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            upsam_buf5_ce1 <= ap_const_logic_1;
        else 
            upsam_buf5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    upsam_buf5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, icmp_ln76_reg_475, empty_reg_508, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage4_11001, ap_block_pp0_stage6_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            upsam_buf5_we0 <= ap_const_logic_1;
        else 
            upsam_buf5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    upsam_buf5_we1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, icmp_ln76_reg_475, empty_reg_508, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage5_11001, ap_block_pp0_stage7_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (empty_reg_508 = ap_const_lv1_0) and (icmp_ln76_reg_475 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            upsam_buf5_we1 <= ap_const_logic_1;
        else 
            upsam_buf5_we1 <= ap_const_logic_0;
        end if; 
    end process;


    upsamp5_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, upsamp5_out_full_n, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6, ap_block_pp0_stage7, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = 
    ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            upsamp5_out_blk_n <= upsamp5_out_full_n;
        else 
            upsamp5_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    upsamp5_out_din_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, upsam_buf_load_22_reg_635, ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i571115212735_reg_172, ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_181016202834_reg_182, ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_21214222636_reg_192, ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_317192933_reg_202, ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_4232537_reg_212, ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_53032_reg_222, ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_638_reg_232, ap_block_pp0_stage0_01001, ap_block_pp0_stage1_01001, ap_block_pp0_stage2_01001, ap_block_pp0_stage3_01001, ap_block_pp0_stage4_01001, ap_block_pp0_stage5_01001, ap_block_pp0_stage6_01001, ap_block_pp0_stage7_01001)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                upsamp5_out_din <= upsam_buf_load_22_reg_635;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage6_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
                upsamp5_out_din <= ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_638_reg_232;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                upsamp5_out_din <= ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_53032_reg_222;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                upsamp5_out_din <= ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_4232537_reg_212;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                upsamp5_out_din <= ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_317192933_reg_202;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                upsamp5_out_din <= ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_21214222636_reg_192;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                upsamp5_out_din <= ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i_181016202834_reg_182;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                upsamp5_out_din <= ap_phi_reg_pp0_iter1_arrayidx18_0_0_0_load_i571115212735_reg_172;
            else 
                upsamp5_out_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            upsamp5_out_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    upsamp5_out_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001, ap_block_pp0_stage5_11001, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) 
    or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            upsamp5_out_write <= ap_const_logic_1;
        else 
            upsamp5_out_write <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln84_fu_371_p2 <= (div15_i_udiv_reg_494 xor ap_const_lv4_8);
    zext_ln82_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln82_fu_438_p1),64));
    zext_ln84_16_cast_fu_344_p3 <= (ap_const_lv1_1 & div15_i_udiv_cast_cast_reg_503);
    zext_ln84_16_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln84_16_cast_fu_344_p3),64));
    zext_ln84_17_cast_fu_356_p3 <= (ap_const_lv1_1 & div15_i_udiv_reg_494);
    zext_ln84_17_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln84_17_cast_fu_356_p3),64));
    zext_ln84_18_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln84_fu_376_p1),64));
    zext_ln84_19_cast_fu_385_p3 <= (ap_const_lv1_1 & div15_i_udiv_cast_fu_368_p1);
    zext_ln84_19_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln84_19_cast_fu_385_p3),64));
    zext_ln84_20_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln84_fu_401_p2),64));
    zext_ln84_21_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln84_4_fu_412_p1),64));
    zext_ln84_22_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln84_5_fu_446_p1),64));
    zext_ln84_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(div15_i_udiv_reg_494),64));
end behav;
