// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module encode_pool2 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        conv2_out19_dout,
        conv2_out19_num_data_valid,
        conv2_out19_fifo_cap,
        conv2_out19_empty_n,
        conv2_out19_read,
        pool2_out20_din,
        pool2_out20_num_data_valid,
        pool2_out20_fifo_cap,
        pool2_out20_full_n,
        pool2_out20_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] conv2_out19_dout;
input  [1:0] conv2_out19_num_data_valid;
input  [1:0] conv2_out19_fifo_cap;
input   conv2_out19_empty_n;
output   conv2_out19_read;
output  [31:0] pool2_out20_din;
input  [1:0] pool2_out20_num_data_valid;
input  [1:0] pool2_out20_fifo_cap;
input   pool2_out20_full_n;
output   pool2_out20_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg conv2_out19_read;
reg pool2_out20_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_start;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_done;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_idle;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_ready;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_conv2_out19_read;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool2_out20_din;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool2_out20_write;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_0_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_0_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_1_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_1_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_2_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_2_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_3_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_3_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_4_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_4_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_5_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_5_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_6_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_6_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_7_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_7_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_8_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_8_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_9_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_9_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_10_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_10_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_11_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_11_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_12_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_12_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_13_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_13_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_14_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_14_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_15_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_15_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_16_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_16_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_17_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_17_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_18_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_18_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_19_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_19_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_20_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_20_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_21_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_21_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_22_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_22_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_23_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_23_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_24_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_24_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_25_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_25_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_26_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_26_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_27_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_27_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_28_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_28_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_29_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_29_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_30_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_30_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_31_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_31_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_32_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_32_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_33_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_33_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_34_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_34_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_35_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_35_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_36_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_36_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_37_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_37_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_38_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_38_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_39_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_39_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_40_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_40_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_41_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_41_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_42_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_42_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_43_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_43_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_44_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_44_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_45_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_45_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_46_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_46_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_47_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_47_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_48_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_48_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_49_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_49_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_50_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_50_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_51_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_51_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_52_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_52_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_53_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_53_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_54_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_54_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_55_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_55_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_56_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_56_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_57_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_57_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_58_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_58_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_59_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_59_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_60_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_60_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_61_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_61_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_62_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_62_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_63_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_63_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_64_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_64_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_65_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_65_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_66_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_66_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_67_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_67_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_68_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_68_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_69_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_69_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_70_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_70_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_71_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_71_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_72_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_72_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_73_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_73_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_74_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_74_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_75_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_75_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_76_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_76_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_77_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_77_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_78_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_78_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_79_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_79_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_80_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_80_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_81_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_81_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_82_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_82_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_83_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_83_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_84_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_84_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_85_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_85_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_86_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_86_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_87_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_87_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_88_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_88_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_89_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_89_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_90_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_90_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_91_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_91_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_92_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_92_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_93_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_93_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_94_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_94_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_95_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_95_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_96_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_96_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_97_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_97_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_98_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_98_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_99_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_99_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_100_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_100_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_101_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_101_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_102_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_102_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_103_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_103_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_104_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_104_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_105_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_105_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_106_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_106_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_107_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_107_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_108_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_108_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_109_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_109_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_110_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_110_o_ap_vld;
wire   [31:0] grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_111_o;
wire    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_111_o_ap_vld;
reg    grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_start_reg;
reg    ap_block_state1_ignore_call114;
reg   [31:0] pool_buf2_V_fu_18;
wire    ap_CS_fsm_state2;
reg   [31:0] pool_buf2_V_1_fu_22;
reg   [31:0] pool_buf2_V_2_fu_26;
reg   [31:0] pool_buf2_V_3_fu_30;
reg   [31:0] pool_buf2_V_4_fu_34;
reg   [31:0] pool_buf2_V_5_fu_38;
reg   [31:0] pool_buf2_V_6_fu_42;
reg   [31:0] pool_buf2_V_7_fu_46;
reg   [31:0] pool_buf2_V_8_fu_50;
reg   [31:0] pool_buf2_V_9_fu_54;
reg   [31:0] pool_buf2_V_10_fu_58;
reg   [31:0] pool_buf2_V_11_fu_62;
reg   [31:0] pool_buf2_V_12_fu_66;
reg   [31:0] pool_buf2_V_13_fu_70;
reg   [31:0] pool_buf2_V_14_fu_74;
reg   [31:0] pool_buf2_V_15_fu_78;
reg   [31:0] pool_buf2_V_16_fu_82;
reg   [31:0] pool_buf2_V_17_fu_86;
reg   [31:0] pool_buf2_V_18_fu_90;
reg   [31:0] pool_buf2_V_19_fu_94;
reg   [31:0] pool_buf2_V_20_fu_98;
reg   [31:0] pool_buf2_V_21_fu_102;
reg   [31:0] pool_buf2_V_22_fu_106;
reg   [31:0] pool_buf2_V_23_fu_110;
reg   [31:0] pool_buf2_V_24_fu_114;
reg   [31:0] pool_buf2_V_25_fu_118;
reg   [31:0] pool_buf2_V_26_fu_122;
reg   [31:0] pool_buf2_V_27_fu_126;
reg   [31:0] pool_buf2_V_28_fu_130;
reg   [31:0] pool_buf2_V_29_fu_134;
reg   [31:0] pool_buf2_V_30_fu_138;
reg   [31:0] pool_buf2_V_31_fu_142;
reg   [31:0] pool_buf2_V_32_fu_146;
reg   [31:0] pool_buf2_V_33_fu_150;
reg   [31:0] pool_buf2_V_34_fu_154;
reg   [31:0] pool_buf2_V_35_fu_158;
reg   [31:0] pool_buf2_V_36_fu_162;
reg   [31:0] pool_buf2_V_37_fu_166;
reg   [31:0] pool_buf2_V_38_fu_170;
reg   [31:0] pool_buf2_V_39_fu_174;
reg   [31:0] pool_buf2_V_40_fu_178;
reg   [31:0] pool_buf2_V_41_fu_182;
reg   [31:0] pool_buf2_V_42_fu_186;
reg   [31:0] pool_buf2_V_43_fu_190;
reg   [31:0] pool_buf2_V_44_fu_194;
reg   [31:0] pool_buf2_V_45_fu_198;
reg   [31:0] pool_buf2_V_46_fu_202;
reg   [31:0] pool_buf2_V_47_fu_206;
reg   [31:0] pool_buf2_V_48_fu_210;
reg   [31:0] pool_buf2_V_49_fu_214;
reg   [31:0] pool_buf2_V_50_fu_218;
reg   [31:0] pool_buf2_V_51_fu_222;
reg   [31:0] pool_buf2_V_52_fu_226;
reg   [31:0] pool_buf2_V_53_fu_230;
reg   [31:0] pool_buf2_V_54_fu_234;
reg   [31:0] pool_buf2_V_55_fu_238;
reg   [31:0] pool_buf2_V_56_fu_242;
reg   [31:0] pool_buf2_V_57_fu_246;
reg   [31:0] pool_buf2_V_58_fu_250;
reg   [31:0] pool_buf2_V_59_fu_254;
reg   [31:0] pool_buf2_V_60_fu_258;
reg   [31:0] pool_buf2_V_61_fu_262;
reg   [31:0] pool_buf2_V_62_fu_266;
reg   [31:0] pool_buf2_V_63_fu_270;
reg   [31:0] pool_buf2_V_64_fu_274;
reg   [31:0] pool_buf2_V_65_fu_278;
reg   [31:0] pool_buf2_V_66_fu_282;
reg   [31:0] pool_buf2_V_67_fu_286;
reg   [31:0] pool_buf2_V_68_fu_290;
reg   [31:0] pool_buf2_V_69_fu_294;
reg   [31:0] pool_buf2_V_70_fu_298;
reg   [31:0] pool_buf2_V_71_fu_302;
reg   [31:0] pool_buf2_V_72_fu_306;
reg   [31:0] pool_buf2_V_73_fu_310;
reg   [31:0] pool_buf2_V_74_fu_314;
reg   [31:0] pool_buf2_V_75_fu_318;
reg   [31:0] pool_buf2_V_76_fu_322;
reg   [31:0] pool_buf2_V_77_fu_326;
reg   [31:0] pool_buf2_V_78_fu_330;
reg   [31:0] pool_buf2_V_79_fu_334;
reg   [31:0] pool_buf2_V_80_fu_338;
reg   [31:0] pool_buf2_V_81_fu_342;
reg   [31:0] pool_buf2_V_82_fu_346;
reg   [31:0] pool_buf2_V_83_fu_350;
reg   [31:0] pool_buf2_V_84_fu_354;
reg   [31:0] pool_buf2_V_85_fu_358;
reg   [31:0] pool_buf2_V_86_fu_362;
reg   [31:0] pool_buf2_V_87_fu_366;
reg   [31:0] pool_buf2_V_88_fu_370;
reg   [31:0] pool_buf2_V_89_fu_374;
reg   [31:0] pool_buf2_V_90_fu_378;
reg   [31:0] pool_buf2_V_91_fu_382;
reg   [31:0] pool_buf2_V_92_fu_386;
reg   [31:0] pool_buf2_V_93_fu_390;
reg   [31:0] pool_buf2_V_94_fu_394;
reg   [31:0] pool_buf2_V_95_fu_398;
reg   [31:0] pool_buf2_V_96_fu_402;
reg   [31:0] pool_buf2_V_97_fu_406;
reg   [31:0] pool_buf2_V_98_fu_410;
reg   [31:0] pool_buf2_V_99_fu_414;
reg   [31:0] pool_buf2_V_100_fu_418;
reg   [31:0] pool_buf2_V_101_fu_422;
reg   [31:0] pool_buf2_V_102_fu_426;
reg   [31:0] pool_buf2_V_103_fu_430;
reg   [31:0] pool_buf2_V_104_fu_434;
reg   [31:0] pool_buf2_V_105_fu_438;
reg   [31:0] pool_buf2_V_106_fu_442;
reg   [31:0] pool_buf2_V_107_fu_446;
reg   [31:0] pool_buf2_V_108_fu_450;
reg   [31:0] pool_buf2_V_109_fu_454;
reg   [31:0] pool_buf2_V_110_fu_458;
reg   [31:0] pool_buf2_V_111_fu_462;
reg   [1:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_start_reg = 1'b0;
end

encode_sp_pool_ap_fixed_32_6_5_3_0_1 grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_start),
    .ap_done(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_done),
    .ap_idle(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_idle),
    .ap_ready(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_ready),
    .conv2_out19_dout(conv2_out19_dout),
    .conv2_out19_num_data_valid(2'd0),
    .conv2_out19_fifo_cap(2'd0),
    .conv2_out19_empty_n(conv2_out19_empty_n),
    .conv2_out19_read(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_conv2_out19_read),
    .pool2_out20_din(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool2_out20_din),
    .pool2_out20_num_data_valid(2'd0),
    .pool2_out20_fifo_cap(2'd0),
    .pool2_out20_full_n(pool2_out20_full_n),
    .pool2_out20_write(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool2_out20_write),
    .pool_buf_0_i(pool_buf2_V_fu_18),
    .pool_buf_0_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_0_o),
    .pool_buf_0_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_0_o_ap_vld),
    .pool_buf_1_i(pool_buf2_V_1_fu_22),
    .pool_buf_1_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_1_o),
    .pool_buf_1_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_1_o_ap_vld),
    .pool_buf_2_i(pool_buf2_V_2_fu_26),
    .pool_buf_2_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_2_o),
    .pool_buf_2_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_2_o_ap_vld),
    .pool_buf_3_i(pool_buf2_V_3_fu_30),
    .pool_buf_3_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_3_o),
    .pool_buf_3_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_3_o_ap_vld),
    .pool_buf_4_i(pool_buf2_V_4_fu_34),
    .pool_buf_4_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_4_o),
    .pool_buf_4_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_4_o_ap_vld),
    .pool_buf_5_i(pool_buf2_V_5_fu_38),
    .pool_buf_5_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_5_o),
    .pool_buf_5_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_5_o_ap_vld),
    .pool_buf_6_i(pool_buf2_V_6_fu_42),
    .pool_buf_6_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_6_o),
    .pool_buf_6_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_6_o_ap_vld),
    .pool_buf_7_i(pool_buf2_V_7_fu_46),
    .pool_buf_7_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_7_o),
    .pool_buf_7_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_7_o_ap_vld),
    .pool_buf_8_i(pool_buf2_V_8_fu_50),
    .pool_buf_8_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_8_o),
    .pool_buf_8_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_8_o_ap_vld),
    .pool_buf_9_i(pool_buf2_V_9_fu_54),
    .pool_buf_9_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_9_o),
    .pool_buf_9_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_9_o_ap_vld),
    .pool_buf_10_i(pool_buf2_V_10_fu_58),
    .pool_buf_10_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_10_o),
    .pool_buf_10_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_10_o_ap_vld),
    .pool_buf_11_i(pool_buf2_V_11_fu_62),
    .pool_buf_11_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_11_o),
    .pool_buf_11_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_11_o_ap_vld),
    .pool_buf_12_i(pool_buf2_V_12_fu_66),
    .pool_buf_12_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_12_o),
    .pool_buf_12_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_12_o_ap_vld),
    .pool_buf_13_i(pool_buf2_V_13_fu_70),
    .pool_buf_13_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_13_o),
    .pool_buf_13_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_13_o_ap_vld),
    .pool_buf_14_i(pool_buf2_V_14_fu_74),
    .pool_buf_14_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_14_o),
    .pool_buf_14_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_14_o_ap_vld),
    .pool_buf_15_i(pool_buf2_V_15_fu_78),
    .pool_buf_15_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_15_o),
    .pool_buf_15_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_15_o_ap_vld),
    .pool_buf_16_i(pool_buf2_V_16_fu_82),
    .pool_buf_16_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_16_o),
    .pool_buf_16_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_16_o_ap_vld),
    .pool_buf_17_i(pool_buf2_V_17_fu_86),
    .pool_buf_17_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_17_o),
    .pool_buf_17_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_17_o_ap_vld),
    .pool_buf_18_i(pool_buf2_V_18_fu_90),
    .pool_buf_18_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_18_o),
    .pool_buf_18_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_18_o_ap_vld),
    .pool_buf_19_i(pool_buf2_V_19_fu_94),
    .pool_buf_19_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_19_o),
    .pool_buf_19_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_19_o_ap_vld),
    .pool_buf_20_i(pool_buf2_V_20_fu_98),
    .pool_buf_20_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_20_o),
    .pool_buf_20_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_20_o_ap_vld),
    .pool_buf_21_i(pool_buf2_V_21_fu_102),
    .pool_buf_21_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_21_o),
    .pool_buf_21_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_21_o_ap_vld),
    .pool_buf_22_i(pool_buf2_V_22_fu_106),
    .pool_buf_22_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_22_o),
    .pool_buf_22_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_22_o_ap_vld),
    .pool_buf_23_i(pool_buf2_V_23_fu_110),
    .pool_buf_23_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_23_o),
    .pool_buf_23_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_23_o_ap_vld),
    .pool_buf_24_i(pool_buf2_V_24_fu_114),
    .pool_buf_24_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_24_o),
    .pool_buf_24_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_24_o_ap_vld),
    .pool_buf_25_i(pool_buf2_V_25_fu_118),
    .pool_buf_25_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_25_o),
    .pool_buf_25_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_25_o_ap_vld),
    .pool_buf_26_i(pool_buf2_V_26_fu_122),
    .pool_buf_26_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_26_o),
    .pool_buf_26_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_26_o_ap_vld),
    .pool_buf_27_i(pool_buf2_V_27_fu_126),
    .pool_buf_27_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_27_o),
    .pool_buf_27_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_27_o_ap_vld),
    .pool_buf_28_i(pool_buf2_V_28_fu_130),
    .pool_buf_28_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_28_o),
    .pool_buf_28_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_28_o_ap_vld),
    .pool_buf_29_i(pool_buf2_V_29_fu_134),
    .pool_buf_29_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_29_o),
    .pool_buf_29_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_29_o_ap_vld),
    .pool_buf_30_i(pool_buf2_V_30_fu_138),
    .pool_buf_30_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_30_o),
    .pool_buf_30_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_30_o_ap_vld),
    .pool_buf_31_i(pool_buf2_V_31_fu_142),
    .pool_buf_31_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_31_o),
    .pool_buf_31_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_31_o_ap_vld),
    .pool_buf_32_i(pool_buf2_V_32_fu_146),
    .pool_buf_32_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_32_o),
    .pool_buf_32_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_32_o_ap_vld),
    .pool_buf_33_i(pool_buf2_V_33_fu_150),
    .pool_buf_33_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_33_o),
    .pool_buf_33_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_33_o_ap_vld),
    .pool_buf_34_i(pool_buf2_V_34_fu_154),
    .pool_buf_34_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_34_o),
    .pool_buf_34_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_34_o_ap_vld),
    .pool_buf_35_i(pool_buf2_V_35_fu_158),
    .pool_buf_35_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_35_o),
    .pool_buf_35_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_35_o_ap_vld),
    .pool_buf_36_i(pool_buf2_V_36_fu_162),
    .pool_buf_36_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_36_o),
    .pool_buf_36_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_36_o_ap_vld),
    .pool_buf_37_i(pool_buf2_V_37_fu_166),
    .pool_buf_37_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_37_o),
    .pool_buf_37_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_37_o_ap_vld),
    .pool_buf_38_i(pool_buf2_V_38_fu_170),
    .pool_buf_38_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_38_o),
    .pool_buf_38_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_38_o_ap_vld),
    .pool_buf_39_i(pool_buf2_V_39_fu_174),
    .pool_buf_39_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_39_o),
    .pool_buf_39_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_39_o_ap_vld),
    .pool_buf_40_i(pool_buf2_V_40_fu_178),
    .pool_buf_40_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_40_o),
    .pool_buf_40_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_40_o_ap_vld),
    .pool_buf_41_i(pool_buf2_V_41_fu_182),
    .pool_buf_41_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_41_o),
    .pool_buf_41_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_41_o_ap_vld),
    .pool_buf_42_i(pool_buf2_V_42_fu_186),
    .pool_buf_42_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_42_o),
    .pool_buf_42_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_42_o_ap_vld),
    .pool_buf_43_i(pool_buf2_V_43_fu_190),
    .pool_buf_43_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_43_o),
    .pool_buf_43_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_43_o_ap_vld),
    .pool_buf_44_i(pool_buf2_V_44_fu_194),
    .pool_buf_44_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_44_o),
    .pool_buf_44_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_44_o_ap_vld),
    .pool_buf_45_i(pool_buf2_V_45_fu_198),
    .pool_buf_45_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_45_o),
    .pool_buf_45_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_45_o_ap_vld),
    .pool_buf_46_i(pool_buf2_V_46_fu_202),
    .pool_buf_46_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_46_o),
    .pool_buf_46_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_46_o_ap_vld),
    .pool_buf_47_i(pool_buf2_V_47_fu_206),
    .pool_buf_47_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_47_o),
    .pool_buf_47_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_47_o_ap_vld),
    .pool_buf_48_i(pool_buf2_V_48_fu_210),
    .pool_buf_48_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_48_o),
    .pool_buf_48_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_48_o_ap_vld),
    .pool_buf_49_i(pool_buf2_V_49_fu_214),
    .pool_buf_49_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_49_o),
    .pool_buf_49_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_49_o_ap_vld),
    .pool_buf_50_i(pool_buf2_V_50_fu_218),
    .pool_buf_50_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_50_o),
    .pool_buf_50_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_50_o_ap_vld),
    .pool_buf_51_i(pool_buf2_V_51_fu_222),
    .pool_buf_51_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_51_o),
    .pool_buf_51_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_51_o_ap_vld),
    .pool_buf_52_i(pool_buf2_V_52_fu_226),
    .pool_buf_52_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_52_o),
    .pool_buf_52_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_52_o_ap_vld),
    .pool_buf_53_i(pool_buf2_V_53_fu_230),
    .pool_buf_53_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_53_o),
    .pool_buf_53_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_53_o_ap_vld),
    .pool_buf_54_i(pool_buf2_V_54_fu_234),
    .pool_buf_54_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_54_o),
    .pool_buf_54_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_54_o_ap_vld),
    .pool_buf_55_i(pool_buf2_V_55_fu_238),
    .pool_buf_55_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_55_o),
    .pool_buf_55_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_55_o_ap_vld),
    .pool_buf_56_i(pool_buf2_V_56_fu_242),
    .pool_buf_56_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_56_o),
    .pool_buf_56_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_56_o_ap_vld),
    .pool_buf_57_i(pool_buf2_V_57_fu_246),
    .pool_buf_57_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_57_o),
    .pool_buf_57_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_57_o_ap_vld),
    .pool_buf_58_i(pool_buf2_V_58_fu_250),
    .pool_buf_58_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_58_o),
    .pool_buf_58_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_58_o_ap_vld),
    .pool_buf_59_i(pool_buf2_V_59_fu_254),
    .pool_buf_59_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_59_o),
    .pool_buf_59_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_59_o_ap_vld),
    .pool_buf_60_i(pool_buf2_V_60_fu_258),
    .pool_buf_60_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_60_o),
    .pool_buf_60_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_60_o_ap_vld),
    .pool_buf_61_i(pool_buf2_V_61_fu_262),
    .pool_buf_61_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_61_o),
    .pool_buf_61_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_61_o_ap_vld),
    .pool_buf_62_i(pool_buf2_V_62_fu_266),
    .pool_buf_62_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_62_o),
    .pool_buf_62_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_62_o_ap_vld),
    .pool_buf_63_i(pool_buf2_V_63_fu_270),
    .pool_buf_63_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_63_o),
    .pool_buf_63_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_63_o_ap_vld),
    .pool_buf_64_i(pool_buf2_V_64_fu_274),
    .pool_buf_64_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_64_o),
    .pool_buf_64_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_64_o_ap_vld),
    .pool_buf_65_i(pool_buf2_V_65_fu_278),
    .pool_buf_65_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_65_o),
    .pool_buf_65_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_65_o_ap_vld),
    .pool_buf_66_i(pool_buf2_V_66_fu_282),
    .pool_buf_66_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_66_o),
    .pool_buf_66_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_66_o_ap_vld),
    .pool_buf_67_i(pool_buf2_V_67_fu_286),
    .pool_buf_67_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_67_o),
    .pool_buf_67_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_67_o_ap_vld),
    .pool_buf_68_i(pool_buf2_V_68_fu_290),
    .pool_buf_68_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_68_o),
    .pool_buf_68_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_68_o_ap_vld),
    .pool_buf_69_i(pool_buf2_V_69_fu_294),
    .pool_buf_69_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_69_o),
    .pool_buf_69_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_69_o_ap_vld),
    .pool_buf_70_i(pool_buf2_V_70_fu_298),
    .pool_buf_70_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_70_o),
    .pool_buf_70_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_70_o_ap_vld),
    .pool_buf_71_i(pool_buf2_V_71_fu_302),
    .pool_buf_71_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_71_o),
    .pool_buf_71_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_71_o_ap_vld),
    .pool_buf_72_i(pool_buf2_V_72_fu_306),
    .pool_buf_72_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_72_o),
    .pool_buf_72_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_72_o_ap_vld),
    .pool_buf_73_i(pool_buf2_V_73_fu_310),
    .pool_buf_73_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_73_o),
    .pool_buf_73_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_73_o_ap_vld),
    .pool_buf_74_i(pool_buf2_V_74_fu_314),
    .pool_buf_74_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_74_o),
    .pool_buf_74_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_74_o_ap_vld),
    .pool_buf_75_i(pool_buf2_V_75_fu_318),
    .pool_buf_75_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_75_o),
    .pool_buf_75_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_75_o_ap_vld),
    .pool_buf_76_i(pool_buf2_V_76_fu_322),
    .pool_buf_76_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_76_o),
    .pool_buf_76_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_76_o_ap_vld),
    .pool_buf_77_i(pool_buf2_V_77_fu_326),
    .pool_buf_77_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_77_o),
    .pool_buf_77_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_77_o_ap_vld),
    .pool_buf_78_i(pool_buf2_V_78_fu_330),
    .pool_buf_78_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_78_o),
    .pool_buf_78_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_78_o_ap_vld),
    .pool_buf_79_i(pool_buf2_V_79_fu_334),
    .pool_buf_79_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_79_o),
    .pool_buf_79_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_79_o_ap_vld),
    .pool_buf_80_i(pool_buf2_V_80_fu_338),
    .pool_buf_80_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_80_o),
    .pool_buf_80_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_80_o_ap_vld),
    .pool_buf_81_i(pool_buf2_V_81_fu_342),
    .pool_buf_81_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_81_o),
    .pool_buf_81_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_81_o_ap_vld),
    .pool_buf_82_i(pool_buf2_V_82_fu_346),
    .pool_buf_82_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_82_o),
    .pool_buf_82_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_82_o_ap_vld),
    .pool_buf_83_i(pool_buf2_V_83_fu_350),
    .pool_buf_83_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_83_o),
    .pool_buf_83_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_83_o_ap_vld),
    .pool_buf_84_i(pool_buf2_V_84_fu_354),
    .pool_buf_84_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_84_o),
    .pool_buf_84_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_84_o_ap_vld),
    .pool_buf_85_i(pool_buf2_V_85_fu_358),
    .pool_buf_85_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_85_o),
    .pool_buf_85_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_85_o_ap_vld),
    .pool_buf_86_i(pool_buf2_V_86_fu_362),
    .pool_buf_86_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_86_o),
    .pool_buf_86_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_86_o_ap_vld),
    .pool_buf_87_i(pool_buf2_V_87_fu_366),
    .pool_buf_87_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_87_o),
    .pool_buf_87_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_87_o_ap_vld),
    .pool_buf_88_i(pool_buf2_V_88_fu_370),
    .pool_buf_88_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_88_o),
    .pool_buf_88_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_88_o_ap_vld),
    .pool_buf_89_i(pool_buf2_V_89_fu_374),
    .pool_buf_89_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_89_o),
    .pool_buf_89_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_89_o_ap_vld),
    .pool_buf_90_i(pool_buf2_V_90_fu_378),
    .pool_buf_90_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_90_o),
    .pool_buf_90_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_90_o_ap_vld),
    .pool_buf_91_i(pool_buf2_V_91_fu_382),
    .pool_buf_91_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_91_o),
    .pool_buf_91_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_91_o_ap_vld),
    .pool_buf_92_i(pool_buf2_V_92_fu_386),
    .pool_buf_92_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_92_o),
    .pool_buf_92_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_92_o_ap_vld),
    .pool_buf_93_i(pool_buf2_V_93_fu_390),
    .pool_buf_93_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_93_o),
    .pool_buf_93_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_93_o_ap_vld),
    .pool_buf_94_i(pool_buf2_V_94_fu_394),
    .pool_buf_94_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_94_o),
    .pool_buf_94_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_94_o_ap_vld),
    .pool_buf_95_i(pool_buf2_V_95_fu_398),
    .pool_buf_95_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_95_o),
    .pool_buf_95_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_95_o_ap_vld),
    .pool_buf_96_i(pool_buf2_V_96_fu_402),
    .pool_buf_96_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_96_o),
    .pool_buf_96_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_96_o_ap_vld),
    .pool_buf_97_i(pool_buf2_V_97_fu_406),
    .pool_buf_97_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_97_o),
    .pool_buf_97_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_97_o_ap_vld),
    .pool_buf_98_i(pool_buf2_V_98_fu_410),
    .pool_buf_98_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_98_o),
    .pool_buf_98_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_98_o_ap_vld),
    .pool_buf_99_i(pool_buf2_V_99_fu_414),
    .pool_buf_99_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_99_o),
    .pool_buf_99_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_99_o_ap_vld),
    .pool_buf_100_i(pool_buf2_V_100_fu_418),
    .pool_buf_100_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_100_o),
    .pool_buf_100_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_100_o_ap_vld),
    .pool_buf_101_i(pool_buf2_V_101_fu_422),
    .pool_buf_101_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_101_o),
    .pool_buf_101_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_101_o_ap_vld),
    .pool_buf_102_i(pool_buf2_V_102_fu_426),
    .pool_buf_102_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_102_o),
    .pool_buf_102_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_102_o_ap_vld),
    .pool_buf_103_i(pool_buf2_V_103_fu_430),
    .pool_buf_103_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_103_o),
    .pool_buf_103_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_103_o_ap_vld),
    .pool_buf_104_i(pool_buf2_V_104_fu_434),
    .pool_buf_104_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_104_o),
    .pool_buf_104_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_104_o_ap_vld),
    .pool_buf_105_i(pool_buf2_V_105_fu_438),
    .pool_buf_105_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_105_o),
    .pool_buf_105_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_105_o_ap_vld),
    .pool_buf_106_i(pool_buf2_V_106_fu_442),
    .pool_buf_106_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_106_o),
    .pool_buf_106_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_106_o_ap_vld),
    .pool_buf_107_i(pool_buf2_V_107_fu_446),
    .pool_buf_107_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_107_o),
    .pool_buf_107_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_107_o_ap_vld),
    .pool_buf_108_i(pool_buf2_V_108_fu_450),
    .pool_buf_108_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_108_o),
    .pool_buf_108_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_108_o_ap_vld),
    .pool_buf_109_i(pool_buf2_V_109_fu_454),
    .pool_buf_109_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_109_o),
    .pool_buf_109_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_109_o_ap_vld),
    .pool_buf_110_i(pool_buf2_V_110_fu_458),
    .pool_buf_110_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_110_o),
    .pool_buf_110_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_110_o_ap_vld),
    .pool_buf_111_i(pool_buf2_V_111_fu_462),
    .pool_buf_111_o(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_111_o),
    .pool_buf_111_o_ap_vld(grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_111_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_start_reg <= 1'b0;
    end else begin
        if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_start_reg <= 1'b1;
        end else if ((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_ready == 1'b1)) begin
            grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_100_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_100_fu_418 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_100_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_101_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_101_fu_422 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_101_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_102_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_102_fu_426 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_102_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_103_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_103_fu_430 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_103_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_104_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_104_fu_434 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_104_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_105_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_105_fu_438 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_105_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_106_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_106_fu_442 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_106_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_107_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_107_fu_446 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_107_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_108_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_108_fu_450 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_108_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_109_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_109_fu_454 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_109_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_10_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_10_fu_58 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_10_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_110_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_110_fu_458 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_110_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_111_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_111_fu_462 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_111_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_11_o_ap_vld == 1'b1))) begin
        pool_buf2_V_11_fu_62 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_11_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_12_o_ap_vld == 1'b1))) begin
        pool_buf2_V_12_fu_66 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_12_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_13_o_ap_vld == 1'b1))) begin
        pool_buf2_V_13_fu_70 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_14_o_ap_vld == 1'b1))) begin
        pool_buf2_V_14_fu_74 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_14_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_15_o_ap_vld == 1'b1))) begin
        pool_buf2_V_15_fu_78 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_15_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_16_o_ap_vld == 1'b1))) begin
        pool_buf2_V_16_fu_82 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_16_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_17_o_ap_vld == 1'b1))) begin
        pool_buf2_V_17_fu_86 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_17_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_18_o_ap_vld == 1'b1))) begin
        pool_buf2_V_18_fu_90 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_18_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_19_o_ap_vld == 1'b1))) begin
        pool_buf2_V_19_fu_94 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_19_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_1_fu_22 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_20_o_ap_vld == 1'b1))) begin
        pool_buf2_V_20_fu_98 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_20_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_21_o_ap_vld == 1'b1))) begin
        pool_buf2_V_21_fu_102 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_21_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_22_o_ap_vld == 1'b1))) begin
        pool_buf2_V_22_fu_106 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_22_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_23_o_ap_vld == 1'b1))) begin
        pool_buf2_V_23_fu_110 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_23_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_24_o_ap_vld == 1'b1))) begin
        pool_buf2_V_24_fu_114 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_24_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_25_o_ap_vld == 1'b1))) begin
        pool_buf2_V_25_fu_118 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_25_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_26_o_ap_vld == 1'b1))) begin
        pool_buf2_V_26_fu_122 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_26_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_27_o_ap_vld == 1'b1))) begin
        pool_buf2_V_27_fu_126 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_27_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_28_o_ap_vld == 1'b1))) begin
        pool_buf2_V_28_fu_130 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_28_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_29_o_ap_vld == 1'b1))) begin
        pool_buf2_V_29_fu_134 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_29_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_2_fu_26 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_30_o_ap_vld == 1'b1))) begin
        pool_buf2_V_30_fu_138 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_30_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_31_o_ap_vld == 1'b1))) begin
        pool_buf2_V_31_fu_142 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_31_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_32_o_ap_vld == 1'b1))) begin
        pool_buf2_V_32_fu_146 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_32_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_33_o_ap_vld == 1'b1))) begin
        pool_buf2_V_33_fu_150 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_33_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_34_o_ap_vld == 1'b1))) begin
        pool_buf2_V_34_fu_154 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_34_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_35_o_ap_vld == 1'b1))) begin
        pool_buf2_V_35_fu_158 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_35_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_36_o_ap_vld == 1'b1))) begin
        pool_buf2_V_36_fu_162 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_36_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_37_o_ap_vld == 1'b1))) begin
        pool_buf2_V_37_fu_166 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_37_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_38_o_ap_vld == 1'b1))) begin
        pool_buf2_V_38_fu_170 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_38_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_39_o_ap_vld == 1'b1))) begin
        pool_buf2_V_39_fu_174 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_39_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_3_fu_30 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_40_o_ap_vld == 1'b1))) begin
        pool_buf2_V_40_fu_178 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_40_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_41_o_ap_vld == 1'b1))) begin
        pool_buf2_V_41_fu_182 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_41_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_42_o_ap_vld == 1'b1))) begin
        pool_buf2_V_42_fu_186 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_42_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_43_o_ap_vld == 1'b1))) begin
        pool_buf2_V_43_fu_190 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_43_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_44_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_44_fu_194 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_44_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_45_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_45_fu_198 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_45_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_46_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_46_fu_202 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_46_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_47_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_47_fu_206 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_47_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_48_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_48_fu_210 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_48_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_49_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_49_fu_214 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_49_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_4_fu_34 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_50_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_50_fu_218 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_50_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_51_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_51_fu_222 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_51_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_52_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_52_fu_226 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_52_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_53_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_53_fu_230 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_53_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_54_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_54_fu_234 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_54_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_55_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_55_fu_238 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_55_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_56_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_56_fu_242 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_56_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_57_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_57_fu_246 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_57_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_58_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_58_fu_250 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_58_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_59_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_59_fu_254 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_59_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_5_fu_38 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_60_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_60_fu_258 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_60_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_61_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_61_fu_262 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_61_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_62_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_62_fu_266 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_62_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_63_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_63_fu_270 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_63_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_64_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_64_fu_274 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_64_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_65_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_65_fu_278 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_65_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_66_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_66_fu_282 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_66_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_67_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_67_fu_286 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_67_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_68_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_68_fu_290 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_68_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_69_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_69_fu_294 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_69_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_6_fu_42 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_70_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_70_fu_298 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_70_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_71_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_71_fu_302 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_71_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_72_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_72_fu_306 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_72_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_73_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_73_fu_310 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_73_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_74_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_74_fu_314 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_74_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_75_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_75_fu_318 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_75_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_76_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_76_fu_322 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_76_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_77_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_77_fu_326 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_77_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_78_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_78_fu_330 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_78_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_79_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_79_fu_334 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_79_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_7_fu_46 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_80_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_80_fu_338 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_80_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_81_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_81_fu_342 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_81_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_82_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_82_fu_346 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_82_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_83_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_83_fu_350 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_83_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_84_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_84_fu_354 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_84_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_85_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_85_fu_358 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_85_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_86_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_86_fu_362 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_86_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_87_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_87_fu_366 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_87_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_88_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_88_fu_370 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_88_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_89_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_89_fu_374 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_89_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_8_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_8_fu_50 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_8_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_90_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_90_fu_378 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_90_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_91_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_91_fu_382 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_91_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_92_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_92_fu_386 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_92_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_93_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_93_fu_390 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_93_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_94_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_94_fu_394 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_94_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_95_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_95_fu_398 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_95_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_96_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_96_fu_402 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_96_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_97_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_97_fu_406 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_97_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_98_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_98_fu_410 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_98_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_99_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_99_fu_414 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_99_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_9_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_9_fu_54 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_9_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        pool_buf2_V_fu_18 <= grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool_buf_0_o;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        conv2_out19_read = grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_conv2_out19_read;
    end else begin
        conv2_out19_read = 1'b0;
    end
end

always @ (*) begin
    if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        pool2_out20_write = grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool2_out20_write;
    end else begin
        pool2_out20_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call114 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_start = grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_ap_start_reg;

assign pool2_out20_din = grp_sp_pool_ap_fixed_32_6_5_3_0_1_fu_466_pool2_out20_din;

assign start_out = real_start;

endmodule //encode_pool2
